#------------------------------------------------------------------------------
#-- Copyright (C) 2009 HBM Netherlands B.V.
#-- Schutweg 15a
#-- 5145 NP Waalwijk
#-- The Netherlands
#-- http://www.hbm.com
#-- All rights reserved
#--
#-- The copyright to the computer program(s) herein is the property of
#-- HBM Netherlands B.V. (HBM), Netherlands. The code/program(s)
#-- may be used and/or copied only with the written permission of HBM
#-- or in accordance with the terms and conditions stipulated in the
#-- agreement/contract under which the program(s) have been supplied.
#-- This copyright notice must not be removed.
#--
#-- This Source Code is subject to the
#-- "General supply and license conditions for software"
#-- which is part of the standard terms and conditions of sale from HBM.
#------------------------------------------------------------------------------
#-- Project  :
#-- Filename :
#-- Author   :
#------------------------------------------------------------------------------
#-- File Description:
#--
#--
#--
#--
#------------------------------------------------------------------------------
#-- ChangeLog:
#--
#--
#--
#--
#------------------------------------------------------------------------------

name: GenDaqAPI Python $(Build.SourceBranchName) Inc $(Year:yy)$(DayOfYear)$(Rev:.2rr)

#------------------------------------------------------------------------------
#-- Setup Environment
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#-- Trigger Definition
#------------------------------------------------------------------------------

trigger:
  batch: true
  branches:
    include:
    - 'main'

pr:
  branches:
    include:
      - 'main'

#------------------------------------------------------------------------------
#-- Stages Definition
#------------------------------------------------------------------------------
jobs:
- job: GenDaqAPIPythonUnitTests
  displayName: Build GenDaqAPI Python Unit Tests
  timeoutInMinutes: 10
  pool:
    name: DevOps-Windows-ESW
    demands:
    - hasConda -equals true
  steps:
  - checkout: self
    clean: true
  - task: CondaEnvironment@0
    inputs:
      environmentName: 'ghsapi'
      createOptions: '--file $(Build.SourcesDirectory)\spec-file.txt'
      cleanEnvironment: true
    displayName: Setting up conda environment
  - task: CmdLine@2
    inputs:
      script: |
        call activate ghsapi
        pip install -r $(Build.SourcesDirectory)\requirements.txt
      workingDirectory: './'
    displayName: Installing requirements
  - task: CmdLine@2
    inputs:
      script: |
        call activate ghsapi
        python unittest/test_suite.py
      workingDirectory: './'
    displayName: Executing Unit Tests
  - task: CmdLine@2
    inputs:
      script: |
        call activate ghsapi
        coverage run -m unittest discover
        coverage xml
      workingDirectory: './unittest'
    displayName: Executing coverage for the unit tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Build.SourcesDirectory)\reports\TEST-*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
    condition: always()
    displayName: Publishing Test Results
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)\unittest\coverage.xml'
    condition: always()
    displayName: Publishing Code Coverage
